# Generated by Django 3.1.4 on 2020-12-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_county'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ('objectid',), 'verbose_name_plural': 'Counties'},
        ),
        migrations.AddField(
            model_name='headquarter',
            name='description',
            field=models.CharField(default='National Offie', max_length=50),
            preserve_default=False,
        ),
    ]
