# Generated by Django 3.1.4 on 2020-12-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20201203_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldoffice',
            name='issue',
            field=models.CharField(choices=[('WATER', 'Water'), ('EROSION', 'Erosion'), ('EDUCATION', 'Education'), ('HEALTH', 'Health')], default='WATER', max_length=100),
        ),
        migrations.AddField(
            model_name='fieldoffice',
            name='number_of_staff',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
